# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title			: Leo Stexo
title_separator         : "|"
email			: blog@stexo.eu
description		: >- # this means to ignore newlines until "baseurl:"
  This is my personal project Blog. Here I am publishing the work on projects I am doing privately.
  Electronics is the main topic, but anything of interest will be possible. 
baseurl			: "" # the subpath of your site, e.g. /blog
url			: "https://blog.stexo.eu"
github_username		: leostx


#theme: minima
#remote_theme: mmistakes/jekyll-theme-basically-basic
#remote_theme: mmistakes/jekyll-theme-hpstr
#remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

remote_theme		: mmistakes/minimal-mistakes
minimal_mistakes_skin   : "default"

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: false
      comments: false
      share: false
      related: false
      show_date: true

atom_feed:
  hide: true

footer:
  links:
    - label: "Rss feed"
      icon: "fas fa-fw fa-rss"
      url: "https://blog.stexo.eu/feed.xml"   
    - label "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:blog@stexo.eu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/leostx"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
